# Generated by Django 4.1.4 on 2023-06-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='isRequest',
            new_name='is_request',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default="Texte apparaissant sur la page de recherche.\n\n\n---\n\nLe texte sous les tirets n'apparait que quand on clique sur l'annonce.\n"),
        ),
    ]
