# Generated by Django 4.1.4 on 2023-10-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_abstract_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.CharField(default='Texte apparaissant sur la page de recherche.', max_length=255),
        ),
    ]
