# Generated by Django 5.2.5 on 2026-01-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default="Texte apparaissant que quand la personne clique sur l'annonce.\n"),
        ),
    ]
