# Generated by Django 5.2.10 on 2026-02-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='org_comment',
            field=models.TextField(blank=True, default="Commentaire visible seulement des membres de l'organisation.\n"),
        ),
    ]
