# Generated by Django 4.1.4 on 2023-01-01 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('contact', models.EmailField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('isIndividual', models.BooleanField(default=False)),
                ('managers', models.ManyToManyField(blank=True, related_name='organizations', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='myorganizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
