# Generated by Django 5.2.5 on 2026-01-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_organizations', '0002_organization_name_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='isIndividual',
        ),
    ]
